"""add whatsapp media url

Revision ID: 0ef8a1ca198a
Revises: 2f7f23280655
Create Date: 2026-09-28 18:59:54.023236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef8a1ca198a'
down_revision: Union[str, Sequence[str], None] = '2f7f23280655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_messages', sa.Column('media_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_messages', 'media_url')
    # ### end Alembic commands ###
