"""add restaurant branding

Revision ID: 163142a03708
Revises: bf3e5077b4f5
Create Date: 2026-10-01 19:57:32.080216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163142a03708'
down_revision: Union[str, Sequence[str], None] = 'bf3e5077b4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "restaurants",
        sa.Column(
            "banner_url",
            sa.String(length=500),
            nullable=True,
        ),
    )

    op.add_column(
        "restaurants",
        sa.Column(
            "tagline",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.add_column(
        "restaurants",
        sa.Column(
            "primary_color",
            sa.String(length=20),
            nullable=False,
            server_default="#18181B",
        ),
    )

    op.add_column(
        "restaurants",
        sa.Column(
            "secondary_color",
            sa.String(length=20),
            nullable=False,
            server_default="#FAF9F6",
        ),
    )

    op.add_column(
        "restaurants",
        sa.Column(
            "accent_color",
            sa.String(length=20),
            nullable=False,
            server_default="#F97316",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'accent_color')
    op.drop_column('restaurants', 'secondary_color')
    op.drop_column('restaurants', 'primary_color')
    op.drop_column('restaurants', 'tagline')
    op.drop_column('restaurants', 'banner_url')
    # ### end Alembic commands ###
