"""add combos and combo items

Revision ID: 3963c79abfe1
Revises: 9cffcfbe6bd5
Create Date: 2026-10-01 21:32:53.250057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3963c79abfe1'
down_revision: Union[str, Sequence[str], None] = '9cffcfbe6bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combos_id'), 'combos', ['id'], unique=False)
    op.create_index(op.f('ix_combos_restaurant_id'), 'combos', ['restaurant_id'], unique=False)
    op.create_table('combo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combo_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['combo_id'], ['combos.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combo_items_combo_id'), 'combo_items', ['combo_id'], unique=False)
    op.create_index(op.f('ix_combo_items_id'), 'combo_items', ['id'], unique=False)
    op.create_index(op.f('ix_combo_items_product_id'), 'combo_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_combo_items_product_id'), table_name='combo_items')
    op.drop_index(op.f('ix_combo_items_id'), table_name='combo_items')
    op.drop_index(op.f('ix_combo_items_combo_id'), table_name='combo_items')
    op.drop_table('combo_items')
    op.drop_index(op.f('ix_combos_restaurant_id'), table_name='combos')
    op.drop_index(op.f('ix_combos_id'), table_name='combos')
    op.drop_table('combos')
    # ### end Alembic commands ###
