"""add campaign image

Revision ID: 7d809e52a2fb
Revises: e5ad61da9b7c
Create Date: 2026-09-28 12:13:51.659386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d809e52a2fb'
down_revision: Union[str, Sequence[str], None] = 'e5ad61da9b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'image_url')
    # ### end Alembic commands ###
