"""add recommendation config

Revision ID: 9cffcfbe6bd5
Revises: 163142a03708
Create Date: 2026-10-01 20:40:26.254034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cffcfbe6bd5'
down_revision: Union[str, Sequence[str], None] = '163142a03708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('upsell_enabled', sa.Boolean(), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('max_recommendations', sa.Integer(), nullable=False),
    sa.Column('min_cart_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('show_after_add', sa.Boolean(), nullable=False),
    sa.Column('show_in_cart', sa.Boolean(), nullable=False),
    sa.Column('show_before_checkout', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_configs_id'), 'recommendation_configs', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_configs_restaurant_id'), 'recommendation_configs', ['restaurant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_configs_restaurant_id'), table_name='recommendation_configs')
    op.drop_index(op.f('ix_recommendation_configs_id'), table_name='recommendation_configs')
    op.drop_table('recommendation_configs')
    # ### end Alembic commands ###
