"""add users table

Revision ID: bf3e5077b4f5
Revises: 3051a2eaadd1
Create Date: 2026-09-29 17:28:31.667904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3e5077b4f5'
down_revision: Union[str, Sequence[str], None] = '3051a2eaadd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_restaurant_id'), 'users', ['restaurant_id'], unique=False)
    op.drop_constraint(op.f('uq_coupons_restaurant_code'), 'coupons', type_='unique')
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=False)
    op.drop_constraint(op.f('restaurants_slug_key'), 'restaurants', type_='unique')
    op.drop_index(op.f('ix_restaurants_slug'), table_name='restaurants')
    op.create_index(op.f('ix_restaurants_slug'), 'restaurants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurants_slug'), table_name='restaurants')
    op.create_index(op.f('ix_restaurants_slug'), 'restaurants', ['slug'], unique=False)
    op.create_unique_constraint(op.f('restaurants_slug_key'), 'restaurants', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.create_unique_constraint(op.f('uq_coupons_restaurant_code'), 'coupons', ['restaurant_id', 'code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_restaurant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
